spring:

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test-db
    username: sa
    password: